name: deploy_to_fedora

on:
  # Se activa al crear o actualizar un Pull Request a la rama 'main' (Verificación)
  pull_request:
    branches:
      - main
  
  # Se activa al hacer push a 'main' (Despliegue Final tras el merge)
  push:
    branches:
      - main

jobs:
  # Job 1: Verificación de Código (Se ejecuta en el Pull Request)
  verify_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4
        
      - name: Verificación de Archivos Estáticos
        run: |
          echo "Contenido del repositorio verificado. Archivo index.html listo."
          ls -l index.html

  # Job 2: Despliegue Final (SOLO se ejecuta al fusionar (merge) el PR en main)
  deploy:
    # Depende de que el trabajo anterior 'verify_code' haya sido exitoso.
    needs: verify_code
    # CRÍTICO: SOLO se ejecuta cuando el evento es un 'push' (al hacer merge a main).
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      - name: Despliegue de index.html vía SFTP a Fedora (Usando ngrok)
        uses: appleboy/scp-action@v0.1.7 
        with:
          # Host dinámico proporcionado por ngrok (ej: 2.tcp.ngrok.io)
          host: ${{ secrets.SSH_HOST }}       
          # Username de tu Fedora (josesfedora)
          username: ${{ secrets.SSH_USERNAME }}
          # Clave SSH privada para la autenticación
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Puerto dinámico proporcionado por ngrok (ej: 12734)
          port: ${{ secrets.SSH_PORT }} 
          # Origen: solo el index.html
          source: "./index.html" 
          # Destino final en tu servidor Apache/Nginx
          target: "/var/www/html/" 
          # Borra archivos viejos antes de subir (limpieza)
          rm: true
